describe('Primer prueba de portales', () => {
    beforeEach(() => {
        cy.visit('https://demoqa.ohmyfi.com/demo/iniciodemo?token=b152dae0f7474a61237add342afe9ea1be93cca187e923aabc702667ba5f0d06&lugar=4089');
    });
    it('relleno de formulario!', () => {
        cy.get('.form-control[name="nombre_completo"]')
            .wait(1000)
            .type('jonathan',{force: true})
        cy.get('.form-control[name="celular"]')
            .wait(1000)
            .type('3136659978')
        cy.get('#seccion_checkhabeas')
            .check()
        cy.get('#pagina_formulario form button[type="submit"]')
            .click()
    })
    it('error relleno de formulario!', () => {
        cy.get('#pagina_formulario form button[type="submit"]')
            .wait(3000)
            .click()
        cy.get('.form-control[name="nombre_completo"]')
            .wait(1000)
            .type('jonathan',{force: true})
        cy.get('.form-control[name="celular"]')
            .wait(1000)
            .type('3136659978')
        cy.get('#pagina_formulario form button[type="submit"]')
            .click()
        cy.get('#seccion_checkhabeas')
            .check()
        cy.get('#pagina_formulario form button[type="submit"]')
            .click()
    })
    it('Solicitud Tokin Wifi', () => {
        cy.get('.form-control[name="nombre_completo"]')
            .type('jonathan',{force: true})
        cy.get('.form-control[name="celular"]')
            .type('3136659978', {force: true})
        cy.get('#seccion_checkhabeas')
            .wait(3000)
            .check()
        cy.get('#pagina_formulario form button[type="submit"]')
            .click()
        // AQUI REALIZO LA PRUEBA DE TOKEN WIFI
        cy.get('#inputTokenWifi')
            .wait(2000)
            .type('12345')
        cy.get('#btnTokenWifi')
            .click()
    })
    it('Preguntas', () => {
        cy.get('.form-control[name="nombre_completo"]')
            .type('jonathan',{force: true})
        cy.get('.form-control[name="celular"]')
            .type('3136659978', {force: true})
        cy.get('#seccion_checkhabeas')
            .wait(3000)
            .check()
        cy.get('#pagina_formulario form button[type="submit"]')
            .click()
        cy.get('#inputTokenWifi')
            .type('12345', {force: true})
        cy.get('#btnTokenWifi')
            .click()
        // AQUI REALIZO LA PRUEBA DE PREGUNTA
        cy.get('#preguntas_seccion div > .btn-pregunta:nth-child(1)')
            .click()
    })
})
