name: Cypress tests
on:
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
