name: Cypress tests
on:
  pull_request:
      types:
        - closed
  # Trigger analysis when pushing in master or pull requests, and when creating
  # push:
  #   branches: [master]
  #   types: [opened, synchronize]
  # pull_request:
  #   branches: [master]
  #   types: [opened, synchronize]
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    cypress-run:
      name: Cypress run
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Cypress.io
          uses: cypress-io/github-action@v4
          with:
            # build: npm run build
            # start: npm start
            start: npm run
            record: true
          env:          
            CYPRESS_RECORD_KEY: ${{ secrets.RECORD_KEY }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
