name: Cypress Test
on:
  pull_request:
      types: [opened, synchronize, reopened]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          start: npm start
