name: Cypress tests
on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches: [master]
    types: [opened, synchronize]
  pull_request:
    branches: [master]
    types: [opened, synchronize]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress.io
        uses: cypress-io/github-action@v4
        with:
          start: npm run
