name: Cypress Test
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Cypress.io
        uses: cypress-io/github-action@v4.2.0
        with:
          start: npm start
